### ISSUE TITLE
Not working behind authenticated proxy

### ISSUE THREAD

**Issue by lechuckcaptain** [bitbar/testdroid-gradle-plugin#11]
The testdroid Gradle plugin seems to not work behind authenticated proxy. All other gradle tasks work flawlessly just setting the gradle.properties file with following parameters:

HTTP:

systemProp.http.proxyHost=
systemProp.http.proxyPort=
systemProp.http.proxyUser=
systemProp.http.proxyPassword=
systemProp.http.nonProxyHosts=

HTTPS: 

systemProp.https.proxyHost=
systemProp.https.proxyPort=
systemProp.https.proxyUser=
systemProp.https.proxyPassword=
systemProp.https.nonProxyHosts=

![image](https://cloud.githubusercontent.com/assets/341895/6557704/5584f598-c677-11e4-9a93-e63518a4372b.png)

**Comment by srautiai** [comment]
Thanks for reporting this. The gradle plugin uses testdroid-api(https://github.com/bitbar/testdroid-api) to communicate with testdroid api and it has proxy support. I will modify it so that if proxy params are set those will be used with API.

**Comment by srautiai** [comment]
#13 Added support for authenticated http proxy(v1.3.1)
