### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by bkmalkoc** [bitbar/testdroid-gradle-plugin#19]
The build is failed with proper configuration on build with the following command;
gradlew testdroidUploadDevelopmentDebugAndroidTest

:app:incrementalDevelopmentDebugAndroidTestJavaCompilationSafeguard
:app:javaPreCompileDevelopmentDebugAndroidTest
:app:compileDevelopmentDebugAndroidTestJavaWithJavac
:app:compileDevelopmentDebugAndroidTestNdk UP-TO-DATE
:app:compileDevelopmentDebugAndroidTestSources
:app:mergeDevelopmentDebugAndroidTestShaders
:app:compileDevelopmentDebugAndroidTestShaders
:app:generateDevelopmentDebugAndroidTestAssets
:app:mergeDevelopmentDebugAndroidTestAssets
:app:transformClassesWithJarMergingForDevelopmentDebugAndroidTest
:app:transformClassesWithMultidexlistForDevelopmentDebugAndroidTest
:app:transformClassesWithDexForDevelopmentDebugAndroidTest
Dex: warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.ccil.cowan.tagsoup.Parser$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

:app:mergeDevelopmentDebugAndroidTestJniLibFolders
:app:transformNativeLibsWithMergeJniLibsForDevelopmentDebugAndroidTest
:app:processDevelopmentDebugAndroidTestJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDevelopmentDebugAndroidTest
:app:validateSigningDevelopmentDebugAndroidTest
:app:packageDevelopmentDebugAndroidTest
:app:assembleDevelopmentDebugAndroidTest
:app:testdroidUploadDevelopmentDebugAndroidTest
TESTDROID: Using APIClientType OAUTH
:app:testdroidUploadDevelopmentDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:testdroidUploadDevelopmentDebugAndroidTest'.
> com.testdroid.api.APIList cannot be cast to com.testdroid.api.model.APIFiles

**Comment by snieguu** [comment]
Hi @bkmalkoc,
could You post your build.gradle because I can't reproduce Your issue

**Comment by winsontan520** [comment]
I encounter same error when upload to testdroid.
Below are the some specs and details of my machine and build.gradle:

OS: MacOS Sierra 10.12.6
Tool: Android Studio 3.0
Java version "1.8.0_122-ea"
Android Gradle plugin used: classpath 'com.android.tools.build:gradle:2.3.3'
Testdroid plugin used: classpath 'com.testdroid:gradle:1.4.0'
apply plugin: 'testdroid'
compileSdkVersion 25
buildToolsVersion "25.0.3"
minSdkVersion 16
targetSdkVersion 25

cmd used: ./gradlew testdroidUpload

let me know if you need more details

**Comment by snieguu** [comment]
Hi @winsontan520 problem is that you use version 1.4.0 of com.testdroid:gradle it is not compatible anymore with newest version of https://cloud.testdroid.com/ (Same problem is in your case @bkmalkoc). Please use at least 1.5.0 or newer.

**Comment by snieguu** [comment]
Hi @winsontan520 problem is that you use version 1.4.0 of com.testdroid:gradle it is not compatible anymore with newest version of https://cloud.testdroid.com/ (Same problem is in your case @bkmalkoc). Please use at least 1.5.0 or newer.

**Comment by winsontan520** [comment]
Using 1.5.0 is working now. Thanks.
You might need to update your guide to use 1.5.0
