### ISSUE TITLE
Not compatible with Android Gradle plugin 1.1.0

### ISSUE THREAD

**Issue by grujo** [bitbar/testdroid-gradle-plugin#9]
The plugin does not work with the latest Android build tools (v1.1.0).
When trying to apply the Testdroid plugin the build fails with the following error:

```
Error:Could not find matching constructor for: com.testdroid.TestDroidServer(com.testdroid.TestDroidExtension_Decorated, org.gradle.api.logging.Logging$LoggerImpl)
```

**Comment by lechuckcaptain** [comment]
Please keep updated the README and/or the [Releases section](https://github.com/bitbar/testdroid-gradle-plugin/releases) with the latest supported version of the plugin

**Comment by nilsi** [comment]
Im still having this problem. What versions are supported?
